### ISSUE TITLE
netcdf-fortran does not appear in search

### ISSUE THREAD

**Issue by Chrismarsh** [Homebrew/formulae.brew.sh#666] opened 2022-10-25 21:50 UTC
- [ x ] your issue is with the https://formulae.brew.sh website and not the (generated) contents of a given formula/cask page.

## What you were trying to do (and why)
I was looking for the `netcdf-fortran` formula (as I wasn't sure if it was separate). I went to [netcdf](https://formulae.brew.sh/formula/netcdf#default) and then searched from there for `netcdf-fortran` which then does not appear 

## What happened (include screenshots)
 `netcdf-fortran` did not appear despite being an active formula

<img width="782" alt="image" src="https://user-images.githubusercontent.com/630436/197888781-9d4d46d9-d37b-48e0-b7d8-b6f6105d5964.png">

## What you expected to happen

It should appear as any other formula would

**Comment by Bo98** [comment] 2022-10-26 01:33
Thanks, will take a look at this soon. We're due to complete migration to a newer system with Algolia, so I'll check if the issue is there in the new data.

**Comment by Bo98** [comment] 2022-11-20 03:26
Just to show I'm not dead yet: we're still looking into this. We've hit a hard limit of the number of items that can be shown in search and I reached out at the beginning of the month to Algolia about next steps, which we're still waiting on a response for.

**Comment by Chrismarsh** [comment] 2023-01-03 04:08
This remains a problem

**Comment by Bo98** [comment] 2023-02-01 15:45
This is now fixed and the change will be deployed with the next scheduled push (probably ~20 minutes).

**Closed by Bo98** 2023-02-01 15:45 UTC
Labels: help wanted
