### ISSUE TITLE
Searching for `blue-jeans` shows no results, but the package exists

### ISSUE THREAD

**Issue by ReagentX** [Homebrew/formulae.brew.sh#308] opened 2020-07-26 00:40 UTC
- [x] your issue is with the https://formulae.brew.sh website and not the (generated) contents of a given formula/cask page.

## What you were trying to do (and why)

- Search for the `blue-jeans` cask

## What happened (include screenshots)

No results:

<img width="731" alt="image" src="https://user-images.githubusercontent.com/1920666/88468826-1a12d400-ceb7-11ea-8bea-ea77d2e39688.png">

## What you expected to happen

The result appears: https://formulae.brew.sh/cask/blue-jeans

**Comment by vp2177** [comment] 2020-07-26 22:14
Just wanted to add that this affects many other formulae, not just `blue-jeans`. 

Another example:
![Screenshot 2020-07-26 at 23 05 15](https://user-images.githubusercontent.com/451903/88490740-b6130d00-cf95-11ea-9560-fb804c50dc19.png)

**Comment by SMillerDev** [comment] 2020-07-27 05:29
Duplicate of https://github.com/Homebrew/formulae.brew.sh/issues/175

**Comment by SMillerDev** [comment] 2020-07-27 05:30
@s-pace you resolved it last time. Could you have a look again?

**Comment by s-pace** [comment] 2020-07-27 08:29
@SMillerDev on it

**Comment by s-pace** [comment] 2020-07-27 08:51
Crawl done on our end. 
![image](https://user-images.githubusercontent.com/32097720/88522639-f3f44d80-cff6-11ea-9848-1d6f1ab19f3f.png)
Issue solved. We will increase the crawl's maximum duration.

**Comment by MikeMcQuaid** [comment] 2020-07-27 09:12
Great, thanks @s-pace!

**Closed by MikeMcQuaid** 2020-07-27 09:12 UTC

**Comment by SMillerDev** [comment] 2020-07-27 09:19
Does it not do a complete crawl regularly?

**Comment by vp2177** [comment] 2020-08-01 11:17
The issue is back:
![Screenshot 2020-08-01 at 12 15 57](https://user-images.githubusercontent.com/451903/89100683-e83ac980-d3f0-11ea-8663-c955e78bdcc9.png)

**Comment by s-pace** [comment] 2020-08-03 08:06
The crawl happened at 2020-08-03 02:04:30.153 CEST until 2020-08-03 03:10:20.130 CEST. It seems that the maximum duration is still too short. We will increase it. In the meantime, I am running the crawl locally without limitation.

**Comment by pvarga-dni** [comment] 2020-10-28 12:29
@s-pace Just a heads up, it looks like this issue is back again
