### ISSUE TITLE
Search: Can't find python

### ISSUE THREAD

**Issue by xobs** [Homebrew/formulae.brew.sh#177] opened 2019-09-15 02:13 UTC
I'm trying to figure out what Homebrew packages there are for Python.  In particular, I'm looking for Python header files in order to build a Boost::Python module.

However, the search doesn't appear to be useful.  If I type in "python" and hit `Enter`, depending on where my mouse is I'm either taken to `python-markdown` or to another site on the page.

Additionally, the only `python` listed is `python@2`, however I can edit the URL to remove the `@2` and go directly to https://formulae.brew.sh/formula/python#default so I know that package exists.

![image](https://user-images.githubusercontent.com/238325/64915755-37f4b000-d7a1-11e9-9d4d-29134770f57b.png)

**Comment by reitermarkus** [comment] 2019-09-15 04:16
Duplicate of https://github.com/Homebrew/formulae.brew.sh/issues/175.

**Closed** 2019-09-15 04:15 UTC
Labels: duplicate
